sudo: false
cache:
  directories: 
  - $HOME/.gradle
  
language: java

jdk:
  - oraclejdk8
  - openjdk7

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/31a671345ecfdce18046
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: [always|never|change] default: always

before_install: 
 - pip install --user codecov
install: ./gradlew assemble -DexcludeBenchmark
script: ./gradlew check -DexcludeBenchmark
after_success: 
 - ./gradlew buildDistributions -DexcludeBenchmark
 - codecov
