language: java

jdk:
  - openjdk6
  - openjdk7
script:
  ant -f make/build.xml jar prepare-tests dist

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/31a671345ecfdce18046
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
