sudo: false
cache:
  directories:
  - "$HOME/.gradle"
language: java
jdk:
- oraclejdk8
- openjdk7
notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/31a671345ecfdce18046
    on_success: change
    on_failure: always
    on_start: never
before_install:
- pip install --user codecov
install: "./gradlew assemble -DexcludeBenchmark"
script: "./gradlew check -DexcludeBenchmark"
after_success:
- "./gradlew buildDistributions -DexcludeBenchmark"
- codecov
deploy:
  provider: bintray
  file: "bintray.json"
  user: "jbachorik"
  key:
    secure: I+Lvki1TM2pQPJEf75U098GSQexgjudOZ2TDCPSQEdGys7PdW7SIy5THiHYdCG+tO8dSKQ3FUXufDD1KzhHxEBSWUX1rpAgE3SGvxYwzAU+bl3FvoQzjb+WD69ya86h0TFM2fVOJsg4+iDimheHcD+7mCuYx3ga1dsi8lVjh38s=
  on:
    all_branches: true 
